### ISSUE TITLE
hide ur "config.py"

### ISSUE THREAD

**Issue by xjackk** [jordandeang/twitch-chat-highlighter#1]
secret = "supercoolsecret" (-:

this looks kinda sick, you should start up development on this again, i'd love to help write some ajax for this.. 

xo

**Comment by jordandeang** [comment]
fixed

yeah I might get back on this, thanks dude.

**Comment by xjackk** [comment]
wasn't to be a dick lol, just tryna help a negro out

some people scrape for those kinda things ): 

just add "config" to the git ignore!

**Comment by jordandeang** [comment]
lmao no worries I do appreciate it really. I'm tryna soup up my contribution wall like yours and not be a scrub. I'll probably get on this project again if I don't find something else to work on
